name: stat_tool_dev
channels:
  - openalea3
  - conda-forge
dependencies:
  - python
  - scikit-build-core
  - setuptoools-scm
  - setuptools
  - cmake
  - pip
  - boost
  - matplotlib-base
  - pip:
      - -e '..[test,dev,doc]'
